---
title: "List of published trait datasets and databases"
subtitle: "Towards an Ecological Trait-data Standard - Supplementary Material A"
author:
- name: Florian D. Schneider \footnotemark[1]  \footnotemark[2]
- name: David Fichtmüller \footnotemark[5]
- name: Martin M. Gossner \footnotemark[8]
- name: Anton Güntsch \footnotemark[5]
- name: Malte Jochum \footnotemark[4]
- name: Birgitta König-Ries\footnotemark[6]
- name: Gaëtane Le Provost \footnotemark[2]
- name: Pete Manning \footnotemark[2]
- name: Andreas Ostrowski \footnotemark[6]
- name: Caterina Penone \footnotemark[4]
- name: Nadja K. Simons \footnotemark[7]
fontsize: 12pt
geometry: margin=0.5in
documentclass: scrartcl
classoption: landscape
output:
  pdf_document:
    fig_caption: yes
    fig_crop: no
    keep_tex: yes
    template: pretty.template
  html_document:
    fig_caption: yes
    fig_width: 4
    highlight: null
    keep_md: yes
    theme: united
  word_document:
    fig_caption: yes
    fig_width: 6
---

\renewcommand{\thefootnote}{\fnsymbol{footnote}}

\footnotetext[1]{Corresponding author: florian.dirk.schneider@gmail.com}
\footnotetext[2]{Senckenberg Biodiversity and Climate Research Centre (BiK-F) Frankfurt am Main, Germany}
\footnotetext[5]{Botanic Garden and Botanical Museum Berlin, Freie Universität Berlin, Berlin, Germany}
\footnotetext[8]{Forest Entomology, Swiss Federal Research Institute WSL, Birmensdorf, Switzerland} <!--  Zürcherstrasse 111, CH-8903 -->
\footnotetext[4]{Institute of Plant Sciences, University of Bern, Bern, Switzerland}
\footnotetext[6]{Department of Mathematics and Computer Science, Friedrich-Schiller-Universität Jena, Jena, Germany}
\footnotetext[7]{Department of Ecology and Ecosystem Management, Technische Universität München, Freising, Germany}

\newpage

\renewcommand{\thetable}{A\arabic{table}}

```{r, echo = FALSE, warning = FALSE}
options(knitr.table.format = "latex")
library(kableExtra)

gg <- read.csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vTfQOIHjJv5x_YHgq14DR7VLTvycfsl2Njj2Ip4p2a5kca8AX5t5cmaial6Bg-MX9pBDOJaJfnlR7Qj/pub?output=csv", encoding = "UTF-8")
dt <- subset(gg, select = c(datasetName, type, DOI, organismFocus, regionalFocus, NumberTaxa, NumberTraits, Responsible, CiteAs, TermsOfUse))

#dt$DOI <- paste0("[http://dx.doi.org/", gg$DOI, "](", gg$DOI, ")")
URL <- sapply(as.character(gg$URL), function(x) unlist(strsplit(x, split = "\n"))[1] )
URL_resolved <- paste0("\\href{",URL,"}{", sapply(URL, substr, start = 1, stop = 30), "... \\ExternalLink} ") #
dt$DOI <- paste0("\\href{http://dx.doi.org/", gg$DOI, "}{", gg$DOI, " \\ExternalLink} ") 
empty <- which(dt$DOI %in% c("\\href{http://dx.doi.org/NA}{NA \\ExternalLink} ", "\\href{http://dx.doi.org/}{ \\ExternalLink} "))
dt$DOI[empty] <- URL_resolved[empty]

#dt$DOI <-  cell_spec(gg$DOI, "latex", link = paste0("http://dx.doi.org/", gg$DOI ) )
caption = paste0("Collection of trait datasets and databases; excerpt of the living spreadsheet at https://goo.gl/QxzfHy (access date ", format(Sys.time(), '%Y-%m-%d'), ")")

order <- c(14, 15,  # all organisms
           1,4,5,13,18,20,21, # plants
           11,16,25,30,33, # all animals
           3,17,31, ## birds
           7,34,12, # mammals
           26,8,27, # other vertebrates
           32,2, 6,9,23,10,22,29,19, # invertebrates
           24,28 # fungi
           # other
           )

kable(dt[order,], longtable=TRUE, escape = FALSE, row.names = FALSE,
      caption = caption,
      booktabs = T) %>%
kable_styling(latex_options = c("scale_down", "repeat_header"), font_size = 6) %>%
  column_spec(1, width = "15em") %>%
  column_spec(2, width = "5em") %>%
  column_spec(3, width = "16em") %>%
  column_spec(4, width = "6em") %>%
  column_spec(5, width = "6em") %>%
  column_spec(6, width = "5em") %>%
  column_spec(7, width = "5em") %>%
  column_spec(8, width = "8em") %>%
  column_spec(9, width = "25em") %>%
  column_spec(10, width = "11em") 
```

